web: can't use c_allocator
When targetting wasm32, even saying ".link_libc = true" doesn't let us
use the c_allocator.  The browser bombs with a message like:

LinkError: import object field 'malloc' is not a Function

Luckily zig's GeneralPurposeAllocator works in wasm32, so we'll use
that.