build.zig: implement lazy dependencies
The usage of lazy dependencies in build.zig.zon suggests dvui intends to
avoid fetching dependencies for backends that it is not currently
building.  However, this requires that the `b.lazyDependency` function
only be called when that backend is actually enabled.  This means having
to add build options that avoid calling `b.lazyDependency` when applicable.

In addition, it's also nice to still see all the build steps even if
the build options for backends have not been given.  To accomplish this,
I've added `BackendDisabledStep` which can be substituted in for any
step when it's associated backend has not been enabled.  This step will
print a nice error message informing the user how to enable the backend:

```sh
$ zig build sdl-standalone
+- Assert sdl backend is disabled failure
error: the sdl backend requires either -Dsdl to fetch/build its lazy dependencies or --system sdl2 to use the system package
Build Summary: 0/2 steps succeeded; 1 failed (disable with --summary none)
sdl-standalone transitive failure
+- Assert sdl backend is disabled failure
error: the following build command failed with exit code 1:
C:\git\dvui\.zig-cache\o\af161e5d03a51c0d4c1d598e4941a320\build.exe D:\bin\zig\0.13.0\files\zig.exe C:\git\dvui C:\git\dvui\.zig-cache C:\Users\Jonathan\AppData\Local\zig --seed 0x304864c -Zdd4b5c3ef8c742eb sdl-standalone
```

I've also updated the compile/run step descriptions to show the builld
options they require, i.e.

```
C:\git\dvui>zig build --help
Usage: D:\bin\zig\0.13.0\files\zig.exe build [steps] [options]

Steps:
  install (default)            Copy build artifacts to prefix path
  uninstall                    Remove build artifacts from prefix path
  compile-sdl-standalone       Compile sdl-standalone (requires -Dsdl or --system sdl2)
  sdl-standalone               Run sdl-standalone (requires -Dsdl or --system sdl2)
  compile-sdl-ontop            Compile sdl-ontop (requires -Dsdl or --system sdl2)
  sdl-ontop                    Run sdl-ontop (requires -Dsdl or --system sdl2)
  compile-raylib-standalone    Compile raylib-standalone (requires -Draylib)
  raylib-standalone            Run raylib-standalone (requires -Draylib)
  compile-raylib-ontop         Compile raylib-ontop (requires -Draylib)
  raylib-ontop                 Run raylib-ontop (requires -Draylib)
...
```