Backends: Remove error catch since these now return void
When building a project with an SDL backend, these errors are thrown.

src/backends/sdl.zig:1957:61: error: expected error union type, found 'void'
    appState.back.setCursor(appState.win.cursorRequested()) catch return c.SDL_APP_FAILURE;

This patch fixes this error by removing the `catch` block since there
are no union errors.

Signed-off-by: Robert Stefanic <rstefanic72@gmail.com>