mach: use texture.release() instead of .destroy() because sometimes we get:
error: gpu: validation error: Destroyed texture [Texture] used in a submit.

Unsure if release() is needed or if this is a bug somewhere else.